export const sample_foods: any[] = [
  {
    id: "1",
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 400,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "assets/food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Meatball",
    price: 350,
    cookTime: "20-30",
    favorite: true,
    origins: ["persia", "middle east", "china"],
    stars: 4.7,
    imageUrl: "assets/food-2.jpg",
    tags: ["SlowFood", "Lunch"],
  },
  {
    id: "3",
    name: "Hamburger",
    price: 380,
    cookTime: "10-15",
    favorite: false,
    origins: ["germany", "us"],
    stars: 3.5,
    imageUrl: "assets/food-3.jpg",
    tags: ["FastFood", "Hamburger"],
  },
  {
    id: "4",
    name: "Fried Potatoes",
    price: 90,
    cookTime: "15-20",
    favorite: true,
    origins: ["belgium", "france"],
    stars: 3.3,
    imageUrl: "assets/food-4.jpg",
    tags: ["FastFood", "Fry"],
  },
  {
    id: "5",
    name: "Chicken Soup",
    price: 210,
    cookTime: "40-50",
    favorite: false,
    origins: ["india", "asia"],
    stars: 3.0,
    imageUrl: "assets/food-5.jpg",
    tags: ["SlowFood", "Soup"],
  },
  {
    id: "6",
    name: "Beyaynet",
    price: 190,
    cookTime: "40-50",
    favorite: false,
    origins: ["Ethiopia"],
    stars: 4.0,
    imageUrl: "assets/food-7.jpg",
    tags: ["FastFood", "Lunch"],
  },
  {
    id: "7",
    name: "Kitfo",
    price: 380,
    cookTime: "20-30",
    favorite: true,
    origins: ["Ethiopia"],
    stars: 4.0,
    imageUrl: "assets/food-8.jpg",
    tags: ["SlowFood", "Lunch"],
  },
  {
    id: "8",
    name: "Shekla tibs",
    price: 370,
    cookTime: "20-30",
    favorite: false,
    origins: ["Ethiopia"],
    stars: 4.0,
    imageUrl: "assets/food-9.jpg",
    tags: ["SlowFood", "Lunch"],
  },
  {
    id: "9",
    name: "Combo",
    price: 360,
    cookTime: "30-40",
    favorite: true,
    origins: ["Ethiopia"],
    stars: 4.0,
    imageUrl: "assets/food-10.jpg",
    tags: ["SlowFood", "Lunch"],
  },
];

export const sample_tags: any[] = [
  { name: "All", count: 9 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 3 },
  { name: "Lunch", count: 6 },
  { name: "SlowFood", count: 4 },
  { name: "Hamburger", count: 1 },
  { name: "Fry", count: 1 },
  { name: "Soup", count: 1 },
];

export const sample_users: any[] = [
  {
    name: "Yordanos Tibe",
    email: "yordanostibebu5@gmail.com",
    password: "12345",
    address: "Ethiopia",
    isAdmin: true,
  },
  {
    name: "Yordanos Tibebu",
    email: "yordanostibebu4@gmail.com",
    password: "12345",
    address: "shanghai",
    isAdmin: false,
  },
];
